### ISSUE TITLE
Show the real name in proper case

### ISSUE THREAD

**Issue by piyushchauhan** [piyushchauhan/iitp-discord-bot#10]
If the name is `PIYUSH CHAUHAN` convert it `Piyush Chauhan`.
https://github.com/piyushchauhan/iitp-discord-bot/blob/459dbe579ae81f856bc8dc7094c5ad7528b849a5/commands/user-info.js#L29
Steps:
- [ ] Split the string with spaces
- [ ] Make the 1st letter of each word capital and all other letters to lowercase. 
- [ ] Rejoin the list of words

**Comment by kushal98** [comment]
Hey Piyush,

I guess the following snippet can solve the issue.

```
let realname = "PIYUSH CHAUHAN"
let name = realname.split(' ')
let newName = []

function convert(item){
  item = item.charAt(0).toUpperCase() + item.slice(1).toLowerCase()
  newName.push(item)
}

name.forEach(convert)
realname = newName.join(' ')
```


Thanks
