### ISSUE TITLE
Add invite to discord server badge in README

### ISSUE THREAD

**Issue by piyushchauhan** [piyushchauhan/iitp-discord-bot#15]
Current Invite link: https://discord.com/oauth2/authorize?client_id=734017321189900400&scope=bot

**Comment by piyushchauhan** [comment]
If possible, make make bot invite link similar to https://discord.com/invite/typicalbot

**Comment by subhangi2731** [comment]
can you please assign this issue to me? @piyushchauhan

**Comment by piyushchauhan** [comment]
Yes this is good to start.

**Comment by dijodaiju7** [comment]
Can you please assign it to me? @piyushchauhan

**Comment by KerinPithawala** [comment]
Can I work on this?

**Comment by piyushchauhan** [comment]
@Kerveyfelix @dijodaiju7 @subhangi2731 Please see the instructions first of [how to contribute](https://github.com/piyushchauhan/iitp-discord-bot#how-to-contribute).
After succcessful installation you will understand the bot working better.

**Comment by dijodaiju7** [comment]
@piyushchauhan How to get bot tokens?

**Comment by piyushchauhan** [comment]
Join the discord server mentioned in readme of the repo and see the #keys channel @dijodaiju7
