### ISSUE TITLE
Log messages in console in better way

### ISSUE THREAD

**Issue by piyushchauhan** [piyushchauhan/iitp-discord-bot#18]
Refer: https://discordjs.guide/miscellaneous/useful-packages.html#chalk
https://discordjs.guide/miscellaneous/useful-packages.html#winston

**Comment by chidaksh** [comment]
please assign this to me @piyushchauhan

**Comment by p-soham11** [comment]
This would be my first time working on a bot. I also want to work on this 😊

**Comment by piyushchauhan** [comment]
@p-soham11 @chidaksh 1st see [How to contribute](https://github.com/piyushchauhan/iitp-discord-bot#how-to-contribute)
