### ISSUE TITLE
Contributors Image In Readme

### ISSUE THREAD

**Issue by Vishal-raj-1** [piyushchauhan/iitp-discord-bot#34]
I think it is a great feature to add contributors image in README file. It really motivate to contributors. It is dynamically order the contributors. 

![contrimga](https://user-images.githubusercontent.com/59874304/102012505-dd198200-3d70-11eb-8e1e-379f47ccd7e2.JPG)

If you want to this feature on README so I want to do this issue @piyushchauhan Sir !! 😄

**Comment by piyushchauhan** [comment]
Ok you can work on this

**Comment by Vishal-raj-1** [comment]
@piyushchauhan Please update my points to +7. This issue and PR is done.

**Comment by Vishal-raj-1** [comment]
> @piyushchauhan Please update my points to +7. This issue and PR is done.

is it done ?

**Comment by piyushchauhan** [comment]
I am keeping the record of the contributors' points in #nwoc-2020 channel in discord server mentioned in readme.

**Comment by Vishal-raj-1** [comment]
> I am keeping the record of the contributors' points in #nwoc-2020 channel in discord server mentioned in readme.

Sure !!
